image: docker:19.03.12

services:
  - docker:19.03.12-dind

before_script:
  - docker info
variables:
  DB_IMAGE: mongo:4.0.26
  DB_CONT: mongodb-cont
  APP_IMAGE_NAME: myapp
  APP_CONT_NAME: app-cont
  NETWORK: app-net 

stages:
  - test
build-project:
  stage: test
  script:
    - docker pull $DB_IMAGE
    - docker network create $NETWORK
    - docker build -t $APP_IMAGE_NAME .
    - dokcer run -d --network=$NETWORK --name $DB_CONT $DB_IMAGE
    - docker run -d -p 4000:4000 --network=$NETWORK --name $APP_CONT_NAME $APP_IMAGE_NAME
testing:
  stage: test
  script:
    - docker exec -it app '/app/node_modules/.bin/tap --reporter=list'
    - docker network rm $NETWORK
    - docker rm -f $APP_CONT_NAME 
    - docker rm -f $DB_CONT