image: docker:19.03.12

services:
  - docker:19.03.12-dind

before_script:
  - docker info
variables:
  DB_IMAGE: mongo:4.0.26
  DB_CONT: backend_mongo_1
  APP_IMAGE_NAME: myapp
  APP_CONT_NAME: app-cont
  NETWORK: app-net 

stages:
  - test
testing:
  stage: test
  script:
    - docker pull $DB_IMAGE
    - docker network create $NETWORK
    - docker build -t $APP_IMAGE_NAME .
    - docker run -d --network=$NETWORK --name $DB_CONT $DB_IMAGE
    - docker run -d --network=$NETWORK -p 4000:4000 --restart unless-stopped --name $APP_CONT_NAME $APP_IMAGE_NAME
    - docker exec $APP_CONT_NAME npm test
    - docker rm -f $APP_CONT_NAME 
    - docker rm -f $DB_CONT
    - docker network rm $NETWORK

