version: '3'
services:
  app:
    image: myapp
    volumes:
      - .:/app
    restart: always
    ports:
      - 4000:4000
    networks:
      - app-net
    depends_on: 
      - mongo
  mongo:
    image: mongo:4.0.26
    # ports:
      # - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - app-net
volumes:
  mongodb:
networks:
  app-net:
