version: '3'
services:
  # nginx:
  #   image: nginx:1
  #   ports: 
  #   - 80:80
  #   volumes: 
  #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    image: myapp
    restart: always
    ports:
      - 4000:4000
    networks:
      - app-net
    depends_on: 
      - mongo
  mongo:
    image: mongo:4.0.26
    # ports:
      # - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - app-net
volumes:
  mongodb:
networks:
  app-net:
