name: acyion-testing

on: [push]

jobs:
  
  job-1-testing-units:
    env
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
    
