name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  testing:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t myapp .

    - name: pull and run mongo
      run: docker pull mongodb && docker run -d -p 27017:27017 --name mongodb-cont mongo

    - name: wait for db to comes up
      run: sleep 10

    - name: run app container
      run: docker run -d -p 4000:4000 --restart unless-stopped --name myapp

    - name: running tests
      run: docker exec $APP_CONT_NAME npm test