name: testing units

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  testing:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t myapp-image .

    - name: create network
      run: docker network create app-net

    - name: pull and run mongo
      run: docker pull mongo && docker run -d --network=app-net -p 27017:27017 --name backend_mongo_1 mongo

    - name: wait for db to comes up
      run: sleep 10

    - name: run app container
      run: docker run -d -p 4000:4000 --network=app-net --restart unless-stopped --name myapp-cont myapp-image 

    - name: running tests
      run: docker exec myapp-cont npm test

    - name: remove containers
      run: docker rm -f myapp-cont backend_mongo_1

    - name: remove network
      run: docker network rm app-net